### ISSUE TITLE
CGP193 : [BUG] Issue Tracker

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#193]
- [x] in new issues form 
  - change parent into category 
  - show the category description and change it when category changes
- [x] inverse the order of listing issues , make the new issues appear first
- [x] send an email when closing the issue
