### ISSUE TITLE
CGP198 : Issue Tracker issues

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#198]
- [x] Every category should have an email , any issue created that belongs to this category should be emailed to this email .
- [x] Issue emails should not be sent to admin 
- [x] Issueemails should contain the issue number

**Comment by lebaz20** [comment]
I observed that Mail templates are not translated, I guess they should
