### ISSUE TITLE
CGP205 : Issue Tracker issues

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#205]
- [x] [High]    only when there is more than one comment per user , edit comment is not working , ajax call is returning fatal error
- [x] [Low] reopen button title is wrong 
- [x] [High]    Create new issue produce a lot of warnings
