### ISSUE TITLE
CGP99: Issue Tracker

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#99]

**Comment by ahmedReda1** [comment]
- [x] creating issue and issue category entities 
- [x] creating issue category admin CRUD 
- [x] creating issue tracker for users
- [x] support multiple upload for issue tracker form 
- [x] list issues for both admin and user 
- [x] adding issue tracker actions
  - [x] new 
  - [x] view
    - [x] create comments entity
    - [x] handle comments forms and view
  - [x] delete
  - [x] close
  - [x] reopen
- [x] sending mail notifications
- [x] adding pager for issue list page
- [x] adding ACL seeds

**Comment by ahmedReda1** [comment]
- [x] adding new parameters to issue entity
  - [x] created By
  - [x] created at

**Comment by babanesma** [comment]
- add javascript confirm box to appear before deleting comments , closing the ticket ( in issues listing and issue page ) or deleting the issue 
- deleting the issue is firing an exception if the issue has comments 

```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`certigate`.`issue_comment`, CONSTRAINT `FK_318C178D5E7AA58C` FOREIGN KEY (`issue_id`) REFERENCES `issue` (`id`))' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
```
- in listing when going to other pages using the paginator , category and status are disappeared
- in listing , change `parents` to `category`

**Comment by ahmedReda1** [comment]
- [x] changing parents to category in issue index
- [x] fix disappearance of status and category in paginator
- [x] cascade on delete issue comments
- [x] adding confirm boxes   
  - [x] delete issue in index
  - [x] delete comments
  - [x] closing the ticket
  - [x] reopening the ticket
- [x] adding links to download issue attachments

**Comment by babanesma** [comment]
Static text translation needed

**Comment by ahmedReda1** [comment]
- [x] adding static text for templates
